import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: { extend: {} },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        devrolin: {
          primary: "#f97316",
          "primary-content": "#ffffff",
          secondary: "#fb923c",
          "secondary-content": "#ffffff",
          accent: "#fdba74",
          neutral: "#374151",
          "base-100": "#1a1a2e",
          "base-200": "#16213e",
          "base-300": "#0f3460",
          "base-content": "#e2e8f0",
          info: "#38bdf8",
          success: "#4ade80",
          warning: "#fbbf24",
          error: "#f87171",
        },
      },
      {
        "neutral-dark": {
          primary: "#f5f5f5",
          "primary-content": "#111214",
          secondary: "#2a2b2f",
          "secondary-content": "#f4f4f5",
          accent: "#3a3b40",
          neutral: "#1f2023",
          "base-100": "#111214",
          "base-200": "#181a1d",
          "base-300": "#212327",
          "base-content": "#f5f5f5",
          info: "#60a5fa",
          success: "#22c55e",
          warning: "#f59e0b",
          error: "#ef4444",
        },
      },
      {
        "neutral-light": {
          primary: "#111827",
          "primary-content": "#ffffff",
          secondary: "#f5f5f5",
          "secondary-content": "#111827",
          accent: "#ececec",
          neutral: "#6b7280",
          "base-100": "#fcfcfc",
          "base-200": "#f7f7f7",
          "base-300": "#eceff1",
          "base-content": "#111827",
          info: "#2563eb",
          success: "#16a34a",
          warning: "#b45309",
          error: "#dc2626",
        },
      },
      {
        pink: {
          primary: "#d946ef",
          "primary-content": "#ffffff",
          secondary: "#f5d0fe",
          "secondary-content": "#701a75",
          accent: "#fbcfe8",
          neutral: "#6b7280",
          "base-100": "#fff7fb",
          "base-200": "#fdf2f8",
          "base-300": "#fce7f3",
          "base-content": "#3b0a2a",
          info: "#60a5fa",
          success: "#22c55e",
          warning: "#f59e0b",
          error: "#ef4444",
        },
      },
      {
        pale: {
          primary: "#334155",
          "primary-content": "#ffffff",
          secondary: "#e2e8f0",
          "secondary-content": "#334155",
          accent: "#dbeafe",
          neutral: "#64748b",
          "base-100": "#f8fafc",
          "base-200": "#f1f5f9",
          "base-300": "#e2e8f0",
          "base-content": "#0f172a",
          info: "#2563eb",
          success: "#16a34a",
          warning: "#d97706",
          error: "#dc2626",
        },
      },
      "light",
      "corporate",
      "retro",
    ],
    defaultTheme: "neutral-dark",
    darkTheme: "neutral-dark",
    logs: false,
  },
};
export default config;
